### ISSUE TITLE
[feature] Add a security policy file

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#541]
I'm not sure this should be handled via an OSSF-org policy or if individual projects needs their own.

@david-a-wheeler can you advise?

From [OpenSSF best practices](https://bestpractices.coreinfrastructure.org/en):

1. [ ] *The project MUST publish the process for reporting vulnerabilities on the project site. {Met URL} [[vulnerability_report_process](https://bestpractices.coreinfrastructure.org/en/criteria/0#0.vulnerability_report_process)]*
1. [ ] *Projects SHOULD fix all critical vulnerabilities rapidly after they are reported. [[vulnerabilities_critical_fixed](https://bestpractices.coreinfrastructure.org/en/criteria/0#0.vulnerabilities_critical_fixed)]*
1. [ ] *The release notes MUST identify every publicly known run-time vulnerability fixed in this release that already had a CVE assignment or similar when the release was created. This criterion may be marked as not applicable (N/A) if users typically cannot practically update the software themselves (e.g., as is often true for kernel updates). This criterion applies only to the project results, not to its dependencies. If there are no release notes or there have been no publicly known vulnerabilities, choose N/A. {N/A justification} [[release_notes_vulns](https://bestpractices.coreinfrastructure.org/en/criteria/0#0.release_notes_vulns)]*
1. [ ] *If private vulnerability reports are supported, the project MUST include how to send the information in a way that is kept private. {N/A allowed} {Met URL} [[vulnerability_report_private](https://bestpractices.coreinfrastructure.org/en/criteria/0#0.vulnerability_report_private)]*
1. [ ] *The project's initial response time for any vulnerability report received in the last 6 months MUST be less than or equal to 14 days. {N/A allowed} [[vulnerability_report_response](https://bestpractices.coreinfrastructure.org/en/criteria/0#0.vulnerability_report_response)]*
1. [ ] *The project MUST have at least one primary developer who knows how to design secure software. (See ‘details’ for the exact requirements.) [[know_secure_design](https://bestpractices.coreinfrastructure.org/en/criteria/0#0.know_secure_design)]* - **Security policy should include info on members of the "security team"**
1. [ ] *At least one of the project's primary developers MUST know of common kinds of errors that lead to vulnerabilities in this kind of software, as well as at least one method to counter or mitigate each of them. [[know_common_errors](https://bestpractices.coreinfrastructure.org/en/criteria/0#0.know_common_errors)]* - **Security policy should include info on members of the "security team"**
1. [ ] *All medium and higher severity exploitable vulnerabilities discovered with static code analysis MUST be fixed in a timely way after they are confirmed. {N/A allowed} [[static_analysis_fixed](https://bestpractices.coreinfrastructure.org/en/criteria/0#0.static_analysis_fixed)]*
1. [ ] *It is SUGGESTED that if the software produced by the project includes software written using a memory-unsafe language (e.g., C or C++), then at least one dynamic tool (e.g., a fuzzer or web application scanner) be routinely used in combination with a mechanism to detect memory safety problems such as buffer overwrites. If the project does not produce software written in a memory-unsafe language, choose "not applicable" (N/A). {N/A allowed} [[dynamic_analysis_unsafe](https://bestpractices.coreinfrastructure.org/en/criteria/0#0.dynamic_analysis_unsafe)]* - **Security policy should point to or outline policy around use of memory-unsafe languages.**
1. [ ] *It is SUGGESTED that the project use a configuration for at least some dynamic analysis (such as testing or fuzzing) which enables many assertions. In many cases these assertions should not be enabled in production builds. [[dynamic_analysis_enable_assertions](https://bestpractices.coreinfrastructure.org/en/criteria/0#0.dynamic_analysis_enable_assertions)]* - **Security policy should include some info and justification on use of static analysis tools**

**Comment by ianlewis** [comment]
Related #547

**Comment by laurentsimon** [comment]
Shall we close this issue then?

**Comment by ianlewis** [comment]
We should have a `SECURITY.md` that at least points to the Open-SSF policy I think.

**Comment by ianlewis** [comment]
The security policy should also identify the "security team" of members that are knowledgeable about security and will address security issues in order to better comply with [OpenSSF security best practices](https://bestpractices.coreinfrastructure.org/en/criteria/0#0.know_secure_design).
