### ISSUE TITLE
[feature] add eslint linter

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#610]
If we are going to have actions written in Typescript we should probably lint the code using [eslint](https://eslint.org/) with [typescript-eslint](https://typescript-eslint.io/)

Related #546 #398

- [x] Add eslint to the compute-sha256 action (#639)
- [ ] Add eslint target to Makefile (#792)
- [ ] Add pre-submit that runs eslint (#792)
- [ ] Update README.md (#792)

**Comment by naveensrinivasan** [comment]
I can work on this.

**Comment by ianlewis** [comment]
Reopen to add support to Makefile and presubmits
