### ISSUE TITLE
[feature] CONTRIBUTING.md documentation.

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#617]
Add information about the logistics of contributing and pointers on how to get started contributing to the project, which issues to look at first, etc.

Probably need something about OpenSSF since it's an OpenSSF project. Does OpenSSF require a CLA? We currently don't enforce that.

From [OpenSSF best practices](https://bestpractices.coreinfrastructure.org/en):

1. [x] *The project website MUST provide information on how to: obtain, provide feedback (as bug reports or enhancements), and contribute to the software. [[interact](https://bestpractices.coreinfrastructure.org/en/criteria/0#0.interact)]*
2. [x] *The information on how to contribute MUST explain the contribution process (e.g., are pull requests used?) {Met URL} [[contribution](https://bestpractices.coreinfrastructure.org/en/criteria/0#0.contribution)]*
3. [ ] *The information on how to contribute SHOULD include the requirements for acceptable contributions (e.g., a reference to any required coding standard). {Met URL} [[contribution_requirements](https://bestpractices.coreinfrastructure.org/en/criteria/0#0.contribution_requirements)]*

Other tasks:
1. [ ] Add a step-by-step HOWTO on how to create a PR.
2. [ ] Add information on PR title (See: https://github.com/slsa-framework/slsa-github-generator/pull/1493#issuecomment-1376815124)
3. [ ] Add instructions on [DCO](https://github.com/slsa-framework/slsa/blob/main/CONTRIBUTING.md#signing-your-work) and make it mandatory.
4. [ ] Add links to issues filtered by the "help wanted" and "good first issue" labels.

**Comment by naveensrinivasan** [comment]
OpenSSF will require CLA. This is being discussed in TAC. 

cc. @david-a-wheeler

**Comment by ianlewis** [comment]
Should add some instructions on DCO as well. The slsa website repo has a good description.
https://github.com/slsa-framework/slsa/blob/main/CONTRIBUTING.md#signing-your-work
