### ISSUE TITLE
Feature: official release

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#75]
This issue tracks what remains to be done for our first release:
- [x] Decide on versioning: v1 vs v0.0.1?
- [x] https://github.com/slsa-framework/slsa-github-generator-go/issues/34
- [x] https://github.com/slsa-framework/slsa-github-generator-go/issues/37
- [x] https://github.com/slsa-framework/slsa-github-generator-go/issues/30
- [x] slsa-framework/slsa-github-generator#97
- [x] https://github.com/slsa-framework/slsa-github-generator-go/issues/23
- [ ] slsa-framework/slsa-github-generator#89
- [x] slsa-framework/slsa-github-generator#76
- [x] https://github.com/slsa-framework/slsa-github-generator-go/issues/47
- [ ] https://github.com/slsa-framework/slsa-github-generator/issues/11
- [x] https://github.com/slsa-framework/slsa-github-generator-go/issues/106
- [x] https://github.com/slsa-framework/slsa-github-generator-go/issues/105
- [x] https://github.com/slsa-framework/slsa-github-generator/issues/74
- [x] https://github.com/slsa-framework/slsa-github-generator/issues/68
- [x] https://github.com/slsa-framework/slsa-github-generator/issues/62
- [x] https://github.com/slsa-framework/slsa-github-generator/issues/112
- [x] https://github.com/slsa-framework/slsa-github-generator/issues/120
- [x] https://github.com/slsa-framework/slsa-github-generator/issues/140
- [x] https://github.com/slsa-framework/slsa-github-generator/issues/138

To decide:
- [x] https://github.com/slsa-framework/slsa-github-generator-go/issues/62

Nice to have:
- [x] https://github.com/slsa-framework/slsa-github-generator-go/issues/58
- [X] ~~slsa-framework/slsa-github-generator#63~~

**Comment by ianlewis** [comment]
If we can, we should try to add using the following ldflags to `go build` commands for releases.
`-ldflags="-X github.com/slsa-framework/slsa-github-generator/version.Version=X.Y"`

https://github.com/slsa-framework/slsa-github-generator/blob/main/version/version.go

**Comment by laurentsimon** [comment]
Should be do-able using `${{github.ref_name}}`

**Comment by ianlewis** [comment]
I added #410 for the version comment above.

Can we close this issue and close out the Go builder GA milestone? https://github.com/slsa-framework/slsa-github-generator/milestone/1

**Comment by laurentsimon** [comment]
SGTM, yes
