### ISSUE TITLE
[docs] Testing policy

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#895]
From [OpenSSF best practices](https://bestpractices.coreinfrastructure.org/en):

1. [x] *The project MUST have a general policy (formal or not) that as major new functionality is added to the software produced by the project, tests of that functionality should be added to an automated test suite. [[test_policy](https://bestpractices.coreinfrastructure.org/en/criteria/0#0.test_policy)]* - See [CONTRIBUTING.md](https://github.com/slsa-framework/slsa-github-generator/blob/main/CONTRIBUTING.md)
1. [x] *The project MUST have evidence that the [test_policy](https://bestpractices.coreinfrastructure.org/en/criteria/0#test_policy) for adding tests has been adhered to in the most recent major changes to the software produced by the project. [[tests_are_added](https://bestpractices.coreinfrastructure.org/en/criteria/0#0.tests_are_added)]* - **Maybe we need contributor docs on code coverage requirements?**
1. [x] *It is SUGGESTED that this policy on adding tests (see [test_policy](https://bestpractices.coreinfrastructure.org/en/criteria/0#test_policy)) be documented in the instructions for change proposals. [[tests_documented_added](https://bestpractices.coreinfrastructure.org/en/criteria/0#0.tests_documented_added)]* - See [CONTRIBUTING.md](https://github.com/slsa-framework/slsa-github-generator/blob/main/CONTRIBUTING.md)

**Comment by ianlewis** [comment]
The criteria here is met by [CONTRIBUTING.md](https://github.com/slsa-framework/slsa-github-generator/blob/main/CONTRIBUTING.md)
