### ISSUE TITLE
[feature] Fail linters on warnings

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#896]
- [x] yamllint is not currently run in strict mode (#1645)
- [x] shellcheck should explicitly set minimum severity (#1645)
- [x] eslint should set max-warnings to 0 (#1645)

From [OpenSSF best practices](https://bestpractices.coreinfrastructure.org/en):

1. [x] *The project MUST address warnings. {N/A allowed} [[warnings_fixed](https://bestpractices.coreinfrastructure.org/en/criteria/0#0.warnings_fixed)]*
2. [x] *It is SUGGESTED that projects be maximally strict with warnings in the software produced by the project, where practical. {N/A allowed} [[warnings_strict](https://bestpractices.coreinfrastructure.org/en/criteria/0#0.warnings_strict)]*
